### ISSUE TITLE
cannot open Instagram link on a linkstack page

### ISSUE THREAD

**Issue by xyychenchen** [LinkStackOrg/LinkStack#762] opened 2024-04-18 07:58 UTC
### LinkStack version

4.7.7

### Description

I added an Instagram link in the linkstack console, and when I open my linkstack page, clicking the Instagram button doesn't respond at all. The button enlarges and then just stays there. I can only open my Instagram link by right-clicking and opening it in a new tab. The other buttons, like WhatsApp, email, and my website, work fine.

### Details about your system

Version: Windows 11 Education Edition
Version: 23H2
Installation Date: 2022/12/18
Operating System Version: 22631.3447
Experience: Windows Feature Experience Pack 1000.22688.1000.0

System:Linux linkstack 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64
PHP Version 8.2.7

Chrome 124.0.6367.60 (Official Build) (64-bit)

### How to reproduce

I just add Instagram link to my page like a normal user and it just happens, I use the system upgrader to upgrade to the latest version

**Comment by xyychenchen** [comment] 2024-04-18 08:16
i can open the instagram link on my mobile phone, but cannot do it on a pc we browser

**Comment by simonives** [comment] 2024-04-18 08:23
Likely a browser issue then. Try clearing your cache as a first step.

-- 
**************************************This email is from SimonIves.com 
<http://www.simonives.com> based in Australia.
Please delete this email if 
you are not the intended recipient.
**************************************

**Comment by xyychenchen** [comment] 2024-04-18 08:56
> Likely a browser issue then. Try clearing your cache as a first step.
> […](#)
> -- **************************************This email is from SimonIves.com <http://www.simonives.com> based in Australia. Please delete this email if you are not the intended recipient. **************************************

thanks bro, tried, but still not working, but could you help me with the mobile setting, is there another setting for mobile web browser, i use the linkstack docker version , and i use the cloudy storm theme, it looks amazing on my pc web browser, but it looks really horrible on my iphone and android phone chrome, the buttons are moving around, not in the central, and other issues, dont know how to descrive but very ugly

**Comment by talheim-it** [comment] 2024-04-20 16:12
I guess the issue itself is solved? The other issue is related to the theme.

**Comment by xyychenchen** [comment] 2024-05-10 04:49
> I guess the issue itself is solved? The other issue is related to the theme.

depends on device I think

**Comment by MattDevTec** [comment] 2024-10-11 00:03
I cannot reproduce this error so definitely a device or browser problem, hence it working on mobile.

**Comment by JulianPrieber** [comment] 2024-10-12 09:30
Buttons are just the same as any other regular link. I see no reason why or how that could fail.
I'd have to agree this is most likely not an issue on our end.

I'm closing this issue for now. Please report any updates should something like this occur again.

**Closed by JulianPrieber** 2024-10-12 09:30 UTC
