### ISSUE TITLE
Browser (Engine) design compatibility 

### ISSUE THREAD

**Issue by tigexplorer** [LinkStackOrg/LinkStack#411] opened 2023-04-22 22:00 UTC
Platform: `Ubuntu 22.04 LTS`
Server type: `Apache2 ...`
PHP version: `8.1`

[//]: # (Please make sure you have read the system requirements at https://llc.ovh/req before submitting your issue.)

Is there a way for better browser compatibility of custom styled buttons?
See screenshots of 
Gecko/ Firefox  
![Bildschirmfoto vom 2023-04-22 23-43-13](https://user-images.githubusercontent.com/43775552/233808153-2fc9ea9e-90c1-425b-b1fb-e8c63fdd83ee.png)

Blink/ Chromium
![Bildschirmfoto vom 2023-04-22 23-44-36](https://user-images.githubusercontent.com/43775552/233808162-aa4cf029-247b-4035-835a-a8f2b6cba7dd.png)

and WebKit/ Epiphani
![Bildschirmfoto vom 2023-04-22 23-44-08](https://user-images.githubusercontent.com/43775552/233808173-04ae7bd4-8544-457f-a68f-0156aefba71f.png)

**Comment by JulianPrieber** [comment] 2023-05-10 15:03
@tigexplorer I haven't had the time to investigate this sooner.
I cannot reproduce this. However, I cannot confirm for Safari.

But we specifically use WebKit syntax to assure maximum compatibility. Especially Chromium and WebKit should have no problem handling it. The only engine that I could imagine this causing errors is Firefox.

I'm not entirely sure how to continue with this.

**Comment by tigexplorer** [comment] 2023-05-15 08:16
> But we specifically use WebKit syntax to assure maximum compatibility. Especially Chromium and WebKit should have no problem handling it. The only engine that I could imagine this causing errors is Firefox.

Hm, as you can see in the screenshots above, Firefox is the only one, that renders the buttons correctly.

**Comment by tigexplorer** [comment] 2023-05-15 08:30
Here is a screenshot of the style preview (Firefox/ Desktop) and the final display on Chrome for Android 13. 

On Chrome for Android and Desktop (Linux), the buttons styled with a custom color gradient are not displayed correct 

For example, the last two buttons, that are only visible with Firefox, are styled like this
`padding-top : inherit;
padding-bottom :inherit;
padding-left :inherit;
padding-right :inherit;
color :#140e14;
background-image :-moz-linear-gradient(45deg, white 0%, #888888 100%);
border-radius :8px;
font-size :inherit;
font-family :inherit;
border-color :inherit;
border-style :inherit;
border-width :inherit;`

![Bildschirmfoto vom 2023-05-15 10-22-10](https://github.com/LinkStackOrg/LinkStack/assets/43775552/359b65ed-b436-4724-8734-363d066ee13b)

![Screenshot_20230515-101320_1](https://github.com/LinkStackOrg/LinkStack/assets/43775552/b7abebcc-9754-4e20-8f79-9de74ad456b1)

**Comment by tigexplorer** [comment] 2023-05-15 09:07
> But we specifically use WebKit syntax to assure maximum compatibility. Especially Chromium and WebKit should have no problem handling it. The only engine that I could imagine this causing errors is Firefox.

It seems, that's the opposite!

The graphical editor produces `-moz-linear-gradient` instead of `-webkit-linear-gradient` for example. 
It's controllable in the text box of the css code style editor.

**Comment by JulianPrieber** [comment] 2023-05-15 12:07
The editor has a CSS section that even displays what exact styling is used. I'm not sure how this would produce something like that.

![chrome_RfL8qhe9fJ](https://github.com/LinkStackOrg/LinkStack/assets/60265788/c6906c46-0c71-49f8-aef2-3b73d006365d)
![chrome_WI9FEzwo1w](https://github.com/LinkStackOrg/LinkStack/assets/60265788/73c3c8a2-2f41-45c7-b9b9-1fe6b9275fb6)


Our normal button styling does not include the WebKit styling, so switching tot hat instead might actually improve things.

**Comment by JulianPrieber** [comment] 2023-05-15 12:35
The editor chose the styling depending on your browser.
Should be fixed now. This will be included in the next version.

**Closed by JulianPrieber** 2023-05-15 12:35 UTC
Labels: bug, help wanted, can't reproduce
